### ISSUE TITLE
Request: Put the latest headless build in a folder

### ISSUE THREAD

**Issue by chocola-mint** [timcsy/GameAIKart#6]
Hello, I'm from the NTHU team, trying to train RL models over the karting game.

Exporting a headless build would make training **a lot** easier for us, [using Google Colab](https://github.com/dhyeythumar/ML-Agents-with-Google-Colab/blob/master/ML-Agents%20with%20Colab.ipynb).  We would highly appreciate it if you could update the build after every new change made to the project.

Basically, we're asking for [Cloud Build](https://docs.unity3d.com/Manual/UnityCloudBuildVcsGit.html) to be set up here.

This will reduce the need for us to tamper with the state of the project (e.g. changing Player/Build settings), and will make iteration faster on our end.

**Comment by timcsy** [comment]
Thanks for issuing this problem!

From the document of ML-Agents: https://github.com/Unity-Technologies/ml-agents/blob/main/com.unity.ml-agents/Documentation~/com.unity.ml-agents.md#known-limitations

It seems that if we want to collect the visual observations, we can't use the headless mode.
So due to this limitation, we will not provide headless mode.

If after testing you can use the headless mode properly, please tell us and we can add this function to our project, thanks.

Best Regards,
timcsy
